### PR TITLE
updated wallet and blockchain

### PR DESCRIPTION
**Pull request by Justme764**
added print statements to wallet and blockchain and also added the ASCII code to the top of blockchain.  if all is done correctly I will continue.

### CODE REVIEW

**Comment by Justme764** [comment]
I see I created a conflict.  What did I do wrong and won't do it again.  Sorry.

**Comment by Frichetten** [comment]
@Justme764, not a problem! Do you see the "Resolve Conflicts" button? I'm not sure if non-maintainers have access to it. 

The problem is that there is a disagreement in the code between the number of spaces between the block of ANSI Sequence definitions and the class definition. Resolving it is actually really easy (if you have access). Simply remove everything between last ANSI Sequence and the Blockchain class. Then be sure there are 2 spaces between those two things.

**Comment by Justme764** [comment]
ok will do.  thanks

**Comment by Justme764** [comment]
I did see the "Resolve Conflict but didn't have access to change.  Thanks for fixing.

**Comment by Frichetten** [comment]
Not a problem, thank you for commiting :)

**Pull request merged**
